---
- hosts: bot-metacritic-aws
  user: ubuntu
  gather_facts: no
  vars:
   token_bot: "{{ lookup('env','token_bot') }}"
   DATABASE_URL: "{{ lookup('env','DATABASE_URL')}}"

  pre_tasks:
    - name: 'Instalar Python'
      become: yes
      raw: apt-get -y install python-simplejson

  tasks:
  - name: Actualizar sistema
    become: yes
    command: apt-get update

  - name: Instalar essential
    become: yes
    command: apt-get install -y build-essential

  - name: Instalar Git
    become: yes
    command: apt-get install -y git

  - name: Instalar pip3
    become: yes
    command: apt-get install -y python3-pip

  - name: Clonar GitHub
    become: yes
    git: repo=https://github.com/josegob/IV-Proyecto  dest=home/ubuntu/IV-Proyecto clone=yes force=yes

  - name: Instalar requirements
    become: yes
    command: pip3 install -r home/ubuntu/IV-Proyecto/requirements.txt
